type URLType = string;

export type GithubRepositoryData = {
    id: string;
    node_id: string;
    name: 'docs';
    full_name: 'ensdomains/docs';
    private: false;
    // Big
    owner: object;
    html_url: URLType;
    description: string;
    fork: boolean;
    url: URLType;
    forks_url: URLType;
    keys_url: URLType;
    collaborators_url: URLType;
    teams_url: URLType;
    hooks_url: URLType;
    issue_events_url: URLType;
    events_url: URLType;
    assignees_url: URLType;
    branches_url: URLType;
    tags_url: URLType;
    blobs_url: URLType;
    git_tags_url: URLType;
    git_refs_url: URLType;
    trees_url: URLType;
    statuses_url: URLType;
    languages_url: URLType;
    stargazers_url: URLType;
    contributors_url: URLType;
    subscribers_url: URLType;
    subscription_url: URLType;
    commits_url: URLType;
    git_commits_url: URLType;
    comments_url: URLType;
    issue_comment_url: URLType;
    contents_url: URLType;
    compare_url: URLType;
    merges_url: URLType;
    archive_url: URLType;
    downloads_url: URLType;
    issues_url: URLType;
    pulls_url: URLType;
    milestones_url: URLType;
    notifications_url: URLType;
    labels_url: URLType;
    releases_url: URLType;
    deployments_url: URLType;
    created_at: string;
    updated_at: string;
    pushed_at: string;
    git_url: string;
    ssh_url: string;
    clone_url: string;
    svn_url: string;
    homepage: string;
    size: number;
    stargazers_count: number;
    watchers_count: number;
    language: null;
    has_issues: boolean;
    has_projects: boolean;
    has_downloads: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    has_discussions: boolean;
    forks_count: number;
    mirror_url: null;
    archived: boolean;
    disabled: boolean;
    open_issues_count: number;
    license: {
        key: string;
        name: string;
        spdx_id: string;
        url: string;
        node_id: string;
    };
    // Forking
    allow_forking: true;
    // Template
    is_template: boolean;
    web_commit_signoff_required: boolean;
    // Tags
    topics: string[]; // ['alpha', 'docs', 'documentation', 'ens']
    visibility: 'public';
    // Public Stats
    forks: number;
    // Public Stats
    open_issues: number;
    // Public Stats
    watchers: number;
    default_branch: string;
    temp_clone_token: null;
    organization: {
        login: string;
        id: number;
        node_id: string;
        avatar_url: URLType;
        gravatar_id: '';
        url: URLType;
        html_url: URLType;
        followers_url: URLType;
        following_url: URLType;
        gists_url: URLType;
        starred_url: URLType;
        subscriptions_url: URLType;
        organizations_url: URLType;
        repos_url: URLType;
        events_url: URLType;
        received_events_url: URLType;
        type: 'Organization';
        site_admin: boolean;
    };
    network_count: number;
    subscribers_count: number;
};
